import express from "express";
import { getAuths } from "../resolvers/auths/get-auths";
import { creatAuths } from "../resolvers/auths/create-auths";
import { deleteAuths } from "../resolvers/auths/delete-auths";
import { updateAuths } from "../resolvers/auths/update-auths";
export const authRouter = express.Router();
authRouter.get("/", getAuths);
authRouter.post("/", creatAuths);
authRouter.put("/", updateAuths);
authRouter.delete("/", deleteAuths);